name: Auther
version: 1.0-SNAPSHOT
main: pl.teksusik.auther.AutherPlugin
author: teksusik.
api-version: 1.13
commands:
  register:
    aliases:
      - reg
    usage: /register <password> <password>
    permission: auther.player.register
  unregister:
    aliases:
      - unreg
    usage: /unregister <password>
    permission: auther.player.unregister
  login:
    aliases:
      - l
      - log
    usage: /login <password>
    permission: auther.player.login
  code:
    usage: /code <code>
    permission: auther.player.code
  totp:
    usage: /totp ["disable"]
    permission: auther.player.totp
permissions:
  auther.player.register:
    default: true
  auther.player.unregister:
    default: true
  auther.player.login:
    default: true
  auther.player.code:
    default: true
  auther.player.totp:
    default: true